### ISSUE TITLE
Thank You!!!

### ISSUE THREAD

**Issue by viprocket1** [carlosedubarreto/frankmocap_win_install#1]
Hey, thanks for making this. I am struggling to install since 2 days. I tried installing it in wsl2 but wsl shared gpu process is confusing. i tried conda on windows to build but i am stuck on the error below. I am making a blender plugin with frankmocap. thank you. I found your code really helpful. Could i help you in any way to complete your repo ?  

`>> Generating video in ./mocap_output\han_short.mp4                                                                                                         ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers                                                                                            built with gcc 10.2.1 (GCC) 20200726                                                                                                                        configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf                                                                                                         libavutil      56. 51.100 / 56. 51.100                                                                                                                      libavcodec     58. 91.100 / 58. 91.100                                                                                                                      libavformat    58. 45.100 / 58. 45.100                                                                                                                      libavdevice    58. 10.100 / 58. 10.100                                                                                                                      libavfilter     7. 85.100 /  7. 85.100                                                                                                                      libswscale      5.  7.100 /  5.  7.100                                                                                                                      libswresample   3.  7.100 /  3.  7.100                                                                                                                      libpostproc    55.  7.100 / 55.  7.100                                                                                                                    [image2 @ 00000177f4f46280] Pattern type 'glob' was selected but globbing is not supported by this libavformat build                                        D:\Downloads\frankmocap-master\mocap_output\rendered/*.jpg: Function not implemented `

**Comment by carlosedubarreto** [comment]
If you got that error, it means you have an output folder created?

If so, it means it is working for you.

I have that same error, but it didnt bother me because, It seems it is just trying to make a video out of the precessed imagens created in the output folder.

And if you want to get the pkl result that can be converted into FBX, you must add --save_pred_pkl at the and of the command.

like this:
python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl

and if you want to convert to fbx, there is a code Ive changed using VIBE fbx conversion code.


I had the same idea of creating a blender addon to make all of this easier, but i have almost no time, but I can try to help you on that.

And thanks for the help offer. But now I'm just trying to make a simple way for people to install and you could help me testing theses codes on this repository and reporting the error you find.

If you find a way to fix the problem I appreciate the information, or you could do a PR.

**Comment by carlosedubarreto** [comment]
@viprocket1 can you confirm if there is a new forlder created on your frankmocap folder? like this:

![image](https://user-images.githubusercontent.com/4061130/104823961-dcbb4d80-582c-11eb-8525-80292ae985df.png)

**Comment by viprocket1** [comment]
yes , `mocap_output` is created in the main folder.  i followed your suggestion and added `--save_pred_pkl` to the body-mocap command all the pkl files got saved into mocap folder inside mocap_output. ill try to convert it to a fbx file.

**Comment by carlosedubarreto** [comment]
on this link you can see my answer with a code I have changed to use the franckmocap PKL file to convert it to fbx

https://github.com/facebookresearch/frankmocap/issues/50

**Comment by viprocket1** [comment]
i am using your this script for conversion  [https://github.com/facebookresearch/frankmocap/files/5750266/fbx_output_FRANKMOCAP.zip](url) 
i am getting the following traceback 
`Input path: D:\Downloads\frankmocap-master\mocap_output/mocap/00000_prediction_result.pkl 
Output path: D:\Downloads\frankmocap-master\mocap_output/fbx/text.fbx
Processing: D:\Downloads\frankmocap-master\mocap_output/mocap/00000_prediction_result.pkl
Traceback (most recent call last):
  File "fbx_output_FRANKMOCAP.py", line 349, in <module>
    person_id=args.person_id
  File "fbx_output_FRANKMOCAP.py", line 171, in process_poses
    list_dir = os.listdir(pkl_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'mocap_FRANK\\'
Error: Not freed memory blocks: 8, total unfreed memory 0.010223 MB`

thank you.

**Comment by carlosedubarreto** [comment]
Oh I see, it the same file I was showing above.

But there is some problems that I remembered now.

that script i sent just to give an idea, but it was not properly working using it alone.

I just did some alterations on what was already working using VIBE mocap, so if you see the way I'm using it, i'm firing it unside VIBE folder, and getting the PKL inside frankmocap folder (and the arguments ar not working properly, as I set the origin PKL inside the script, hard coded)

![image](https://user-images.githubusercontent.com/4061130/104839363-48d69980-589f-11eb-9340-48d09bec593a.png)


The way it is built, unfortunetely, you will have to install  vibe and hard code to origin of the PKL...
But, the good news, is that I did a tutorial on installing VIBE and the FBX converter.

So you can have frankmocap and VIBE on the same PC using windows, and use the code I sent as a reference so you can make it work for you.

The tutorial I told about is here.

How to install VIBE
https://youtu.be/3qhs5IRJ1LI

How to install VIBE fbx convesion
https://youtu.be/w1biKeiQThY

**Comment by viprocket1** [comment]
Hey , sorry for the late reply. had some covid issues in family. I just want to take some time out for thanking you . I really appreciate the way your solution are detailed and on point. Thanks for making the videos too ( I liked and subbed 👌) . Keep it up man. I am following your instructions . Again I'm really thankful for helping me out.

**Comment by carlosedubarreto** [comment]
Thanks a lot for having the time to try out the solution and to be in contact...

I also would like to wish all the best for you and family, and that you can come out of this damn COVID issue without much problems

Wish you all the best...
