### ISSUE TITLE
I have a problem Pls help

### ISSUE THREAD

**Issue by hamad1027** [carlosedubarreto/frankmocap_win_install#10]
ive done everything in the video twice but when i put this command:
python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output

nothing opens but it says:
![Capture](https://user-images.githubusercontent.com/81476562/112724162-fe1e7100-8f22-11eb-9c01-23f6167e0d93.PNG)

PLS help me

**Comment by carlosedubarreto** [comment]
From what I see, looks like there are som missing files.
It is complaining that it cant find han_sort.mp4

In my pc they are like this
![image](https://user-images.githubusercontent.com/4061130/112729210-cbb44a00-8f09-11eb-8129-8ff9f56e5a4c.png)

does your computer have them?

**Comment by hamad1027** [comment]
No i have it...

![Nope i have it ](https://user-images.githubusercontent.com/81476562/112743090-ea175580-8f9c-11eb-9628-3b1e506df76f.PNG)

**Comment by carlosedubarreto** [comment]
Please run the install bat again and paste the text that shows on your screen so I can see here the problem is happening during the installation.

**Comment by hamad1027** [comment]
you mean this command ? install_win_full_body.bat

or the bat called install_win_full_body ?

**Comment by hamad1027** [comment]
IT WORKED !!! i just ran this command agian install_win_full_body.bat and it worked 

Thanks man

**Comment by hamad1027** [comment]
By the way is there is any way i could use the motion capture in blender ?

**Comment by carlosedubarreto** [comment]
Thanks for the feedback.

About using it in blender, I saw an issue on the original github that someone was about to make a PR with code to convert the pose estimation to something usable .

Here is the link

https://github.com/facebookresearch/frankmocap/issues/47

And I had shared a code that I took from Vibe.

It works, but you have to tweak somethings that are hard coded.
https://github.com/facebookresearch/frankmocap/issues/50#issuecomment-752014586
