### ISSUE TITLE
Stuck during installation

### ISSUE THREAD

**Issue by Aurosutru** [carlosedubarreto/frankmocap_win_install#16]
At a system prompt with Admin rights I enter:

D:\AI-Mocap\FrankMocap\FrankMocapExe>install_win_full_body.bat

The output is:

D:\AI-Mocap\FrankMocap\FrankMocapExe>rem ####### installing files pre packed

D:\AI-Mocap\FrankMocap\FrankMocapExe>REM pip install whl/faster_rcnn-0.1-cp37-cp37m-win_amd64.whl

D:\AI-Mocap\FrankMocap\FrankMocapExe>pip install whl/detectron2-0.3-cp37-cp37m-win_amd64.whl
The system cannot execute the specified program.

D:\AI-Mocap\FrankMocap\FrankMocapExe>pip install whl/opendr-0.73-py3-none-any.whl
The system cannot execute the specified program.

D:\AI-Mocap\FrankMocap\FrankMocapExe>pip install whl/PyOpenGL-3.1.5-cp37-cp37m-win_amd64.whl
The system cannot execute the specified program.

D:\AI-Mocap\FrankMocap\FrankMocapExe>pip install whl/PyOpenGL_accelerate-3.1.5-cp37-cp37m-win_amd64.whl
The system cannot execute the specified program.

D:\AI-Mocap\FrankMocap\FrankMocapExe>pip install -r requirements_alter.txt
The system cannot execute the specified program.

D:\AI-Mocap\FrankMocap\FrankMocapExe>echo Installing a third-party 2D keypoint detector
Installing a third-party 2D keypoint detector

D:\AI-Mocap\FrankMocap\FrankMocapExe>python scripts_py/install_pose2d.py
The system cannot execute the specified program.

D:\AI-Mocap\FrankMocap\FrankMocapExe>echo Download extra data for body module
Download extra data for body module

D:\AI-Mocap\FrankMocap\FrankMocapExe>python scripts_py/download_data_body_module.py
The system cannot execute the specified program.

D:\AI-Mocap\FrankMocap\FrankMocapExe>echo Installing a third-party hand detector
Installing a third-party hand detector

D:\AI-Mocap\FrankMocap\FrankMocapExe>python scripts_py/install_hand_detectors.py
The system cannot execute the specified program.

D:\AI-Mocap\FrankMocap\FrankMocapExe>rem installing the hand object detector

D:\AI-Mocap\FrankMocap\FrankMocapExe>REM "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

D:\AI-Mocap\FrankMocap\FrankMocapExe>set DISTUTILS_USE_SDK=1

D:\AI-Mocap\FrankMocap\FrankMocapExe>cd detectors\hand_object_detector\lib
The system cannot find the path specified.

D:\AI-Mocap\FrankMocap\FrankMocapExe>python setup.py build develop
The system cannot execute the specified program.

D:\AI-Mocap\FrankMocap\FrankMocapExe>cd ../../..

D:\>echo Download extra data for hand module
Download extra data for hand module

D:\>python scripts_py/download_data_hand_module.py
The system cannot execute the specified program.

D:\>echo Downloading sample videos
Downloading sample videos

D:\>python scripts_py/download_sample_video.py
The system cannot execute the specified program.

D:\>

The files appear to be in their folders.  Any suggestions?  Thanks.

**Comment by carlosedubarreto** [comment]
Thats odd. Is miniconda Installed?

**Comment by Aurosutru** [comment]
For some reason I had lots of trouble with installing Miniconda on my system.  It took multiple tries and in the process it exceeded the Windows 2047 character limit for the environment path variable, locking that.  Using the Rapid Environment Editor tool straightened that out, but I eventually had to install Anaconda3, which I had the impression would give me a system-wide python, but not so.  I was also having trouble installing a standalone Python3.8.

I was able to run the final batch file in your instructions by entering the Frankmocap environment in conda and running it from there.  MS PowerShell helpfully provided a hint that the command needed to be preceded by .\ much like Linux.  It wasn't clear whether that command wants to be run from a Windows system prompt or within the Anaconda Frankmocap environment.  If it needs to be at the Windows prompt, it seems I'll need to install a separate Python3.9 since the py and python commands in a PowerShell are not yet giving any result.

Now when running the   .\install_win_full_body.bat   command the error messages highlighted in red include:

 Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\TomMoriarty\.conda\envs\frankmocap\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-zcezbn5v\\pycocotools_af6cfeca37154cafaa4e343515c9497a\\setup.py'"'"'; __file__='"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-zcezbn5v\\pycocotools_af6cfeca37154cafaa4e343515c9497a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\TOMMOR~1\AppData\Local\Temp\pip-wheel-6437lkjw'........

also:

   Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\TomMoriarty\.conda\envs\frankmocap\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-u5kagvdz\\pycocotools_b09ff670b56640f284ecca49233b41b4\\setup.py'"'"'; __file__='"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-u5kagvdz\\pycocotools_b09ff670b56640f284ecca49233b41b4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TOMMOR~1\AppData\Local\Temp\pip-record-ujqlgoka\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\TomMoriarty\.conda\envs\frankmocap\Include\pycocotools'
         cwd: C:\Users\TOMMOR~1\AppData\Local\Temp\pip-install-u5kagvdz\pycocotools_b09ff670b56640f284ecca49233b41b4\
    Complete output (21 lines):
    running install
    running build.........

and:

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\TomMoriarty\.conda\envs\frankmocap\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-zcezbn5v\\pycocotools_af6cfeca37154cafaa4e343515c9497a\\setup.py'"'"'; __file__='"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-zcezbn5v\\pycocotools_af6cfeca37154cafaa4e343515c9497a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TOMMOR~1\AppData\Local\Temp\pip-record-upegpmh1\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\TomMoriarty\.conda\envs\frankmocap\Include\pycocotools'
         cwd: C:\Users\TOMMOR~1\AppData\Local\Temp\pip-install-zcezbn5v\pycocotools_af6cfeca37154cafaa4e343515c9497a\
    Complete output (21 lines):
    running install
    running build........

and:

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\TomMoriarty\.conda\envs\frankmocap\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-u5kagvdz\\pycocotools_b09ff670b56640f284ecca49233b41b4\\setup.py'"'"'; __file__='"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-u5kagvdz\\pycocotools_b09ff670b56640f284ecca49233b41b4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\TOMMOR~1\AppData\Local\Temp\pip-wheel-3airjjqu'
       cwd: C:\Users\TOMMOR~1\AppData\Local\Temp\pip-install-u5kagvdz\pycocotools_b09ff670b56640f284ecca49233b41b4\
  Complete output (23 lines):
  running bdist_wheel
  running build
  running build_py................

and:

    Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\TomMoriarty\.conda\envs\frankmocap\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-u5kagvdz\\pycocotools_b09ff670b56640f284ecca49233b41b4\\setup.py'"'"'; __file__='"'"'C:\\Users\\TOMMOR~1\\AppData\\Local\\Temp\\pip-install-u5kagvdz\\pycocotools_b09ff670b56640f284ecca49233b41b4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TOMMOR~1\AppData\Local\Temp\pip-record-ujqlgoka\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\TomMoriarty\.conda\envs\frankmocap\Include\pycocotools'
         cwd: C:\Users\TOMMOR~1\AppData\Local\Temp\pip-install-u5kagvdz\pycocotools_b09ff670b56640f284ecca49233b41b4\
    Complete output (21 lines):
    running install
    running build
    running build_py....................

with a final error (not in red):

C:\>python scripts_py/download_sample_video.py
python: can't open file 'scripts_py/download_sample_video.py': [Errno 2] No such file or directory
(frankmocap) PS C:\FrankMocapExe>

Will try installing a standalone Python3.9 and see whether that takes care of the errors.

**Comment by carlosedubarreto** [comment]
jeez, I never seen that kind of error.
probably you could try to install it without miniconda, but I must say, sometimes using miniconda is already difficult (and miniconda makes things much easier)

Hope you have success,

**Comment by Aurosutru** [comment]
I managed to install Python3.8.  Here are the errors when running   C:\FrankMocapExe>.\install_win_full_body.bat   in a Windows PowerShell with administrative rights.

C:\FrankMocapExe>pip install whl/detectron2-0.3-cp37-cp37m-win_amd64.whl
ERROR: detectron2-0.3-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.
-----
C:\FrankMocapExe>pip install whl/PyOpenGL-3.1.5-cp37-cp37m-win_amd64.whl
ERROR: PyOpenGL-3.1.5-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.
-----
C:\FrankMocapExe>pip install whl/PyOpenGL_accelerate-3.1.5-cp37-cp37m-win_amd64.whl
ERROR: PyOpenGL_accelerate-3.1.5-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.
-----
    Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TomMoriarty\\AppData\\Local\\Temp\\pip-install-lyboc6hs\\pycocotools_d5035eabb9c6450087738ac2abcc908c\\setup.py'"'"'; __file__='"'"'C:\\Users\\TomMoriarty\\AppData\\Local\\Temp\\pip-install-lyboc6hs\\pycocotools_d5035eabb9c6450087738ac2abcc908c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TomMoriarty\AppData\Local\Temp\pip-record-c6jo_dpw\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python38\Include\pycocotools'
         cwd: C:\Users\TomMoriarty\AppData\Local\Temp\pip-install-lyboc6hs\pycocotools_d5035eabb9c6450087738ac2abcc908c\
    Complete output (23 lines):
    running install.......

-----

C:\>python scripts_py/download_data_hand_module.py
python: can't open file 'scripts_py/download_data_hand_module.py': [Errno 2] No such file or directory

C:\>echo Downloading sample videos
Downloading sample videos

C:\>python scripts_py/download_sample_video.py
python: can't open file 'scripts_py/download_sample_video.py': [Errno 2] No such file or directory

C:\>

These last two errors point to scripts that are in their folder.   Hmmm.  I was able to run them manually by cd'ing to their folder.  Maybe this inability of the script to find files is a cause of some of the above problems.

Updating pip did not help.

Any thoughts on these errors and their solutions?  Thanks.

**Comment by carlosedubarreto** [comment]
Probably the problem is the way you have to run python.

The script consider that you are runnning python from frankmocap root folder. But the way you are executing, probably is setting the root folder on another place.

Another sugestion I would give, would be to had code the full path on the script, so it finds the file, no matter where you are running it from.

**Comment by Aurosutru** [comment]
Was able to get the last two files installed manually.  The other problems related to _.whl is not a supported wheel on this platform_ look more formidable, so I will leave them for now.

From your comments on other websites it seems you are favoring development of EasyMocap now with a Blender plugin.  My main interest is to have body and hand mocap importable into Blender.  Will EasyMocap accomplish that now, or in the near future, more likely than FrankMocap?  If so, will it do so only with multiple cameras?  From the EasyMocap Github page it seems the output from OpenPose, which runs well for me, can be used too.  Is that your understanding?

Thanks again for all your help and advice.

**Comment by carlosedubarreto** [comment]
Each of the solutions got its strong and weak points.

Frankmocap is much more difficult to install on windows platform, the preocessing after installed is very easy, you need anyfootage with a person and takes a aceptable amout of time... and the result is....good,

Easymocap, intalation is one of the easiest for what I saw. the packages for windows worked very well.
the problem, I could only make it work with at least 2 cameras.
to use both cameras, you have to calibrate them, and the calibration takes some time, and if you dont do it well, you will have problems with the result.

But as soon as you understand how it works and get a proper calibration of the cameras (intrinsic) (you have to do it just once) you are good to go.

But you will have to calibrate extrinsicly. If you are like me, that dont have a place to leave the cameras fixed, you will have to calibrate extrinsicaly every time you want to make a mocap data. But that extrinsic is not difficult. I made some videos showing the problems and how to solve them easily.

and the results from easymocap where the best ones, even when you bring it to blender.
you cen see the tutorials I'm made and some results from easymocap in my youtube page
https://www.youtube.com/channel/UC7f8Q6nwrcFsEzpm4vW_Lqg

But, I must say the easymocap tutorial where the worst ones I've made. I was in a rush, and the proccess take too much time.
You can take up to 5h to setup everything, depending on your machine performance.

But man,... if you want to do lots of mocaps using simples cameras, I would suggest you to got with the easymocap approach...

I even stopped searching for another solution because I saw that it was good enought to start my animation project.

**Comment by Aurosutru** [comment]
That is a very complete answer - thank you.  I will continue with questions at your EasyMocap plug-in Git project.
