### ISSUE TITLE
Problems with the installation: ModuleNotFoundError

### ISSUE THREAD

**Issue by SSA4** [carlosedubarreto/frankmocap_win_install#2]
Hello, 

I have some issues with the installation of Frankmocap. Everytime I run  
"python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl"
I get this error:

`Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\miniconda3\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Frank Motion Capture\Frank Mocap\demo\demo_frankmocap.py", line 24, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "D:\Frank Motion Capture\Frank Mocap\handmocap\hand_bbox_detector.py", line 30, in <module>
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named 'model'` 

I dont know why, but I think the Detectron is a part of the problem.
Before this error I get another error:

`Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\miniconda3\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Frank Motion Capture\Frank Mocap\demo\demo_frankmocap.py", line 6, in <module>
    import torch
  File "C:\Users\User\miniconda3\envs\frankmocap\lib\site-packages\torch\__init__.py", line 116, in <module>
    raise err
OSError: [WinError 127] Die angegebene Prozedur wurde nicht gefunden. Error loading "C:\Users\User\miniconda3\envs\frankmocap\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.` 

I searched at Google and someone says that I have to delete the "caffe2_detectron_ops.dll" but now I get this other error.

My system:

I use Miniconda3
Conda 4.9.2
Python 3.8.5
Cudatoolkit=10.1

GPU: NVIDIA Quadro M4000 8GB
Windows 10
CPU: Intel Core i7-7700

I had no problems with the first parts of the installation. Only the last step wont work. Yesterday I had no problems to
install VIBE and the FBX Converter.

**Comment by carlosedubarreto** [comment]
Hello...
What happens if you run this code at frankmocap root folder?

pip install whl/detectron2-0.3-cp37-cp37m-win_amd64.whl

I think maybe some problem appeared when installing Detectron.

**Comment by SSA4** [comment]
If I run this then I get a bunch of lines thats says that the Requirement is already satisfied and
detectron2 is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

I run this in the folder "Frank Mocap" which is the root folder.
(frankmocap) D:\Frank Motion Capture\Frank Mocap>

**Comment by carlosedubarreto** [comment]
try this..

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

see if it works

if it goes allright, do this (run when you are in the frankmocap root)

```
set DISTUTILS_USE_SDK=1
cd detectors\hand_object_detector\lib
python setup.py build develop
```

to go backi to root folder. run 

`cd ../../..`

see if some error will show up.

if not, try to run the example code again
`python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl`

**Comment by carlosedubarreto** [comment]
Closing after long time without response
