### ISSUE TITLE
LINK : fatal error LNK1181

### ISSUE THREAD

**Issue by HeYiHao01** [carlosedubarreto/frankmocap_win_install#25]
Hi, I created a new environment, and follow the steps to install all required packages, but still encountered this problem, which has been bothering me for a long time...

(MyFrankmocap) D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib>python setup.py build develop
running build
running build_py
running build_ext
building 'model._C' extension
Emitting ninja build file D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
D:\SoftWare\VS Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\SoftWare\Anaconda\envs\MyFrankmocap\lib\site-packages\torch\lib /LIBPATH:D:\SoftWare\Cuda10\Development\lib/x64 /LIBPATH:D:\SoftWare\Anaconda\envs\MyFrankmocap\libs /LIBPATH:D:\SoftWare\Anaconda\envs\MyFrankmocap\PCbuild\amd64 "/LIBPATH:D:\SoftWare\VS Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:D:\SoftWare\VS Community\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit__C D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\build\temp.win-amd64-3.7\Release\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\model\csrc\vision.obj D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\build\temp.win-amd64-3.7\Release\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\model\csrc\cpu\nms_cpu.obj D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\build\temp.win-amd64-3.7\Release\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\model\csrc\cpu\ROIAlign_cpu.obj D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\build\temp.win-amd64-3.7\Release\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\model\csrc\cuda\nms.obj D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\build\temp.win-amd64-3.7\Release\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\model\csrc\cuda\ROIAlign_cuda.obj D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\build\temp.win-amd64-3.7\Release\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\model\csrc\cuda\ROIPool_cuda.obj /OUT:build\lib.win-amd64-3.7\model\_C.cp37-win_amd64.pyd /IMPLIB:D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\build\temp.win-amd64-3.7\Release\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\model\csrc\_C.cp37-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“D:\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\build\temp.win-amd64-3.7\Release\PyWorkspace\MOT\PoseEstimation\frankmocap\MyFrankmocap\detectors\hand_object_detector\lib\model\csrc\vision.obj”
error: command 'D:\\SoftWare\\VS Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe' failed with exit status 1181

**Comment by carlosedubarreto** [comment]
Hello, and sorry, I dont have the amount of knowledge to help you on that, but doing some research looks like a problem in the configuration of Visual Studio to compile the hand_object_detector.

here something I found that could help you on that
https://stackoverflow.com/questions/6451324/visual-studio-link-fatal-error-lnk1181-cannot-open-input-file

**Comment by HeYiHao01** [comment]
Thank you so much, I will try, if I can find a solution, I will also give feedback here. Good work by the way, helped me a lot.

**Comment by HeYiHao01** [comment]
I found a solution! By using VS x64_x86 cross tools command build the hand_object_detector with pytorch=1.0.1, then activate the frankmocap environment and run the demo.
