### ISSUE TITLE
'install_win_full_body.bat' is not recognized

### ISSUE THREAD

**Issue by Christopeos** [carlosedubarreto/frankmocap_win_install#27]
(frankmocap) PS C:\MOCAP\Frankmocap> install_win_full_body.bat
install_win_full_body.bat : The term 'install_win_full_body.bat' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ install_win_full_body.bat
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install_win_full_body.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

All necessary components seem to have been installed properly, what am i doing wrong?

**Comment by carlosedubarreto** [comment]
thats odd.
Are youexecuting install_win_full_body.bat inside python?
It should be outside python.

**Comment by Christopeos** [comment]
![image](https://user-images.githubusercontent.com/82039213/130024657-1d678cf2-f06e-4073-b253-e1aabc9020d6.png)

Could you please elaborate further, I have barely any programming experience. This is what I come across, also noticed the visual studio command gives different results to those in the video.

**Comment by carlosedubarreto** [comment]
Now I understand the message.

I though it was an error from python, but it is an error from powershell.
That "PS" after frankmocap stands for powershell.

can you see if the `install_win_full_body.bat` file is in the `c:\mocap\frankmocap` folder?

Because from the error, it seems that the file is not there, for some reason...

**Comment by Christopeos** [comment]
Ah i see now, the file is on a different drive. How do i access that, whatever i try i seem to be stuck on C:

**Comment by carlosedubarreto** [comment]
you could copy the files to that folder.

**Comment by Christopeos** [comment]
Thank you, that fixed it. But i am running into another problem with downloading the SMPL model. The link http://smplify.is.tue.mpg.de/downloads leads to a 404, and when i enter the download section on the smpl website i just cannot find that particular file. Could you please provide an alternative download link? (my apologies if I should be filing this as a separate issue)

**Comment by carlosedubarreto** [comment]
I tested that link just now and worked for me...
Unfortunately I cant provide that file, worst case scenario, I could be sued because of that.

**Comment by Christopeos** [comment]
The page appeared different to me, the file was under another download link. Anyway it worked, thank you very much for the support!
