### ISSUE TITLE
ModuleNotFoundError: No module named 'torchgeometry' (PT-BR)

### ISSUE THREAD

**Issue by wgallo** [carlosedubarreto/frankmocap_win_install#28]
Fiz tudinho, but i think i got something wrong..what am i missing??I would really appreciate any help!!
Traceback (most recent call last):
  File "C:\Users\wgalloGTX\miniconda3\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\wgalloGTX\miniconda3\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\MOCAP\GIT FRANKMOCAP\demo\demo_frankmocap.py", line 16, in <module>
    from bodymocap.body_mocap_api import BodyMocap
  File "C:\MOCAP\GIT FRANKMOCAP\bodymocap\body_mocap_api.py", line 10, in <module>
    from bodymocap.models import hmr, SMPL, SMPLX
  File "C:\MOCAP\GIT FRANKMOCAP\bodymocap\models\__init__.py", line 1, in <module>
    from .hmr import hmr
  File "C:\MOCAP\GIT FRANKMOCAP\bodymocap\models\hmr.py", line 10, in <module>
    from bodymocap.utils.geometry import rot6d_to_rotmat
  File "C:\MOCAP\GIT FRANKMOCAP\bodymocap\utils\geometry.py", line 8, in <module>
    import torchgeometry
ModuleNotFoundError: No module named 'torchgeometry'
![help](https://user-images.githubusercontent.com/25496338/130163577-f543f482-045c-4765-941d-5c358068bfd8.JPG)

**Comment by carlosedubarreto** [comment]
Tem essa dica aqui que a pessoa disse que funcionou

`pip install torchgeometry`

link para a resposta
https://github.com/carlosedubarreto/frankmocap_win_install/issues/11#issuecomment-846609519

**Comment by wgallo** [comment]
CONSEGUI FAZER FUNCIONAR!!!!!! PASSO A PASSO...Entao....como e que eu faco pra passar pra .fbx?? eu vi um monte de perguntas ja...e dificil ou facil usar of VIDE? tem algum tutorial? tenho blender e gostaria de usar lo. Abracos!!!

**Comment by carlosedubarreto** [comment]
O jeito mais facil para passar pra FBX (na minha opinião) é usando um addon que criei pro blender.
Lá tem opção de carregar os dados do frankmocap.

https://carlosedubarreto.gumroad.com/l/mocap_import

O addon é para importar no blender os dados do Frankmocap, e de la voce pode exportar para FBX.

**Comment by wgallo** [comment]
Entao.....uma vez que tenha terminado o processo com o frankmocap, i will
import the resulting file onto blender and then use this program to make it
work?

**Comment by carlosedubarreto** [comment]
Esse é um addon pro blender.
Ele transformaria os dados gerados no frankmocap para um esqueeleto no blender com movimento
