### ISSUE TITLE
Issue when running frankmocap: 'ffmpeg' is not recognized

### ISSUE THREAD

**Issue by Christopeos** [carlosedubarreto/frankmocap_win_install#29]
The program works, the footage is processed, I get the output images but instead of the pkl files I get this error: 'ffmpeg' is not recognized as an internal or external command, operable program or batch file. I have triple checked that ffmpeg is properly installed in the correct folder.

(frankmocap) PS C:\MOCAP> python -m demo.demo_bodymocap --input_path ./mocap_input/mocap1.mp4 --out_dir ./mocap_output
Loading Body Pose Estimator
use_smplx False

Visualization saved: ./mocap_output\rendered\00000.jpg
Time: 14.67 sec/frame, FPS 0.07
Processed : ./mocap_output\frames\00000.jpg

-->more frames here<--

Visualization saved: ./mocap_output\rendered\00124.jpg
Time: 0.19 sec/frame, FPS 5.32
Processed : ./mocap_output\frames\00124.jpg
>> Generating video in ./mocap_output\mocap1.mp4
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kircastudios** [comment]
Did you set **Environment Variable**?

**Comment by kircastudios** [comment]
Ok thats interesting after processing i'll get the same error... thats funny
![Screenshot_6](https://user-images.githubusercontent.com/72751039/130701400-92c5d146-8bd4-467d-9c16-fe62739ea7cb.png)

**Comment by Christopeos** [comment]
> Did you set **Environment Variable**?

And yes, the environment variable is in place

**Comment by carlosedubarreto** [comment]
Hello @kircastudios 
Just to test if the variable is set correctly. you can do this test.

On the command line you type `ffmpeg` and press enter.

it should show something like this
![image](https://user-images.githubusercontent.com/4061130/130741031-7ee1933e-91e3-40d9-8e2b-ea8bc1b37dee.png)


it its not showing, please show the screen that you've setup the variable.

another important thing.
If you had the command line open, and then setup the variable, you should close the cmd and open it again to make the variable work

**Comment by kircastudios** [comment]
@carlosedubarreto Hey! Actually ffmpeg is not working but other things working like a charm. I get .PKL output and imported in blender and no problem. What exactly is the function of ffmpeg in the **last step**?

**Comment by carlosedubarreto** [comment]
To be honest, I'm not sure 😅 I didnt analyze the code. But maybe it is used to create a video with the final result.
