### ISSUE TITLE
from model import _C ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by santutu** [carlosedubarreto/frankmocap_win_install#3]
I have been struggling with this error.
Maybe tourch was installed incorrectly.

I realized that this error is a rather common problem, by googling

```
(frankmocap) D:\desktop\3d\mocap\frankmocap\frankmocap>python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

Traceback (most recent call last):
  File "D:\programfiles\anaconda38\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\programfiles\anaconda38\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\desktop\3d\mocap\frankmocap\frankmocap\demo\demo_frankmocap.py", line 24, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "D:\desktop\3d\mocap\frankmocap\frankmocap\handmocap\hand_bbox_detector.py", line 33, in <module>
    from detectors.hand_object_detector.lib.model.roi_layers import nms # might raise segmentation fault at the end of program
  File "D:\desktop\3d\mocap\frankmocap\frankmocap\detectors\hand_object_detector\lib\model\roi_layers\__init__.py", line 3, in <module>
    from .nms import nms
  File "D:\desktop\3d\mocap\frankmocap\frankmocap\detectors\hand_object_detector\lib\model\roi_layers\nms.py", line 3, in <module>
    from model import _C
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by santutu** [comment]
https://github.com/pytorch/pytorch/issues/4518
https://github.com/pytorch/pytorch/issues/32916

They said about changing python, cuda version.
or not found dll so have to manually downlaod it.
or etc problems...

Current is too late night. 
I will try it and record  at tomorrow

**Comment by carlosedubarreto** [comment]
I would suggest you to try doing this steps that are in the middle of the install_win_body.bat

That is where I think is the most problematic part.

Go to frankmocap root folder
Execute this line
**"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"**

See if it throw an error, if not, execute this:
```
set DISTUTILS_USE_SDK=1
cd detectors\hand_object_detector\lib
python setup.py build develop
cd ../../..
```

it the first commando throws an error, that's maybe the problem, you visual studio is anopther version and the address for the vcvars64.bat may be different.

**Comment by santutu** [comment]
I failed to install on windows.
So I try  wsl2.   https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-cuda-in-wsl
It works

**Comment by asdqe5** [comment]
I have a question that using rtx3080 in this frank mocap project. I need some help how to use rtx3080 and what is the correct version of cuda, cudatoolkit, cudnn and pytorch. please help me.

**Comment by carlosedubarreto** [comment]
Hi @asdqe5 , I tested with a RTX2060, and I had to use CUDA 10.0 and 10.1 to pack some python packages that are hard to install in windows.
Unfortunatelly if your card dont have cuda 10 you´ll have to find a way to install it using another cuda version, and this code in this repository might not work.

Please go to the Frankmocap main repository to see if you find someone to help you with that.

https://github.com/facebookresearch/frankmocap/issues
