### ISSUE TITLE
Opa!! tudo bom? te mandei um email mas...

### ISSUE THREAD

**Issue by wgallo** [carlosedubarreto/frankmocap_win_install#31]
...pode ser que consiga me comunicar melhor contigo por aqui...aqueles comandos pra instalar python e opencv eu tenho que abrir o cmd entao? porque eu tava tentando fazer dentro do blender. outra coisa...quando instalei o frankmocap, eu tive que instalar o python. nao vai dar confusao quando eu fizer estes comandos??

abracos!!! e muito obrigado!!

**Comment by carlosedubarreto** [comment]
Sim, seria para executar os comandos (tipo esse aqui em baixo) no CMD mesmo

`"C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.exe" "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages"\pip install opencv-python`

Em teoria, não deveria dar problema com o python que voce tem instalado, por que voce esta apontando (na primeira parte do codigo) que voce quer rodar com o python que vem dentro do blender.

**Comment by wgallo** [comment]
VALEU !!!!

**Comment by wgallo** [comment]
bah...ta me dando que ambos ja estao instalados (requirement already
satisfied)...mas em outro local no meu comp...o que faco?

**Comment by wgallo** [comment]
https://blenderartists.org/t/how-to-use-my-own-python-installation/629262

nao sei se isso ai em cima da pra fazer...espero que tu tenhas a solucao...

**Comment by carlosedubarreto** [comment]
fechando esse issue e colocando os dados no issue 
https://github.com/carlosedubarreto/frankmocap_win_install/issues/30
