### ISSUE TITLE
already installed...

### ISSUE THREAD

**Issue by wgallo** [carlosedubarreto/frankmocap_win_install#32]
bah...ta me dando que ambos ja estao instalados (requirement already satisfied)...mas em outro local no meu comp...o que faco?

**Comment by wgallo** [comment]
![image](https://user-images.githubusercontent.com/25496338/132075460-4c263161-ca00-46a5-8870-c810ec938c48.png)

**Comment by carlosedubarreto** [comment]
fechando esse issue, pois esta sendo tratado no 
https://github.com/carlosedubarreto/frankmocap_win_install/issues/30
