### ISSUE TITLE
detectron2 install error

### ISSUE THREAD

**Issue by kingaladdin** [carlosedubarreto/frankmocap_win_install#37]
Any idea on how to fix issues with installing detectron2?
after entering "pip install -e."
I get a error code at the last second in red. 
" ERROR: Command errored out with exit status 1:
     command: 'C:\Users\kinga\miniconda3\envs\venv_frankmocap\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kinga\\Desktop\\frankmocap-main\\detectron3-windows\\setup.py'"'"'; __file__='"'"
'C:\\Users\\kinga\\Desktop\\frankmocap-main\\detectron3-windows\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\kinga\Desktop\frankmocap-main\detectron3-windows\
    Complete output (41 lines):
    No CUDA runtime is found, using CUDA_HOME='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v10.2'
    running develop
    running egg_info
    creating detectron2.egg-info
    writing detectron2.egg-info\PKG-INFO
    writing dependency_links to detectron2.egg-info\dependency_links.txt
    writing requirements to detectron2.egg-info\requires.txt
    writing top-level names to detectron2.egg-info\top_level.txt
    writing manifest file 'detectron2.egg-info\SOURCES.txt'
    reading manifest file 'detectron2.egg-info\SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'detectron2.egg-info\SOURCES.txt'
    running build_ext
    building 'detectron2._C' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\Users
    creating build\temp.win-amd64-3.7\Release\Users\kinga
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\box_iou_rotated
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\cocoeval
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\nms_rotated
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\ROIAlign
    creating build\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\ROIAlignRotated
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\include -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\include\TH -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\include\THC -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\include -IC:\Users\kinga\miniconda3\envs\venv_frankmocap\include /EHsc /TpC:\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\vision.cpp /Fobuild\temp.win-amd64-3.7\Release\Users\kinga\Desktop\frankmocap-main\detectron3-windows\detectron2\layers\csrc\vision.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
    C:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    C:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\torch\utils\cpp_extension.py:316: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    error: command 'cl.exe' failed: No such file or directory
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\Users\kinga\miniconda3\envs\venv_frankmocap\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\kinga\miniconda3\envs\venv_frankmocap\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"
'C:\\Users\\kinga\\Desktop\\frankmocap-main\\detectron3-windows\\setup.py'"'"'; __file__='"'"
'C:\\Users\\kinga\\Desktop\\frankmocap-main\\detectron3-windows\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by kingaladdin** [comment]
I apologize about the length and format of the error code. And I'm praying this is the last error I get lol

**Comment by carlosedubarreto** [comment]
I remember when I was building the tutorial for frankmocap, installing the detectron was the most complicated part, thats why I made a compilation of it.
![image](https://user-images.githubusercontent.com/4061130/144753082-c395e3b0-bb6c-4ca8-bc40-5fcf027256c9.png)

And honestly the only thing I remember, was that it was very difficult to do.

To solve your issue, I strongly suggest to go to the official github site and ask there, because I dont have the knowledge to help you with that, sorry.

**Comment by kingaladdin** [comment]
Yeah this is the hardest installation process I've dealt with in my life. I think I'll need some caffeine and spend a whole weekend on this lol. And will do. Thanks for getting back with me though

**Comment by carlosedubarreto** [comment]
I must say that, if you want to have amazing results. to use like a mocap. Frankmocap probably wont be good enough.

And I think detectron is only needed if you want to get the hands movement.
If you are interested in body movement only, i think you can skip this problem you are having.

And im my opinion, I didnt like the hand track that much (i think i didnt geve me the result I should have for the amount of trouble I've got to install it LOL)

But, if you have more than one camera, and you would like to have a better result, even with hand movement (it not fast and the camera calibration part is difficult) you can take a look at easymocap.

On the opposite, the installation is much easier. You will have problems and probably wont have this working on in one day. 

But my experience, is that easymocap had much better results.

**Comment by kingaladdin** [comment]
And here I thought installing pirated pc games before 2009 was the hardest thing to install lol. Thanks for putting me on easymocap. I was shocked to hear about this and threedpose (with unity), an it's amazing that we have more than one option. We've came a looong way. Thanks once again and I pray you have a great Christmas

**Comment by carlosedubarreto** [comment]
Yeah lol....
I understand you.

But about easymocap I got some news.

Today I began coding a solution to use it inside blender. In a way that makes it less confusing to use it.

here is a preview
![image](https://user-images.githubusercontent.com/4061130/144912430-9ab9fa82-db9e-4c7a-96d5-6dc57d1050f7.png)
