### ISSUE TITLE
the SMPL/SMPL-X Models is missing

### ISSUE THREAD

**Issue by Zscqy17** [carlosedubarreto/frankmocap_win_install#38]
![image](https://user-images.githubusercontent.com/53066625/148166182-f64522e2-313f-4d43-ac4c-8170b78d68b8.png)
Hi,

**Comment by carlosedubarreto** [comment]
Sorry, if the models are missing, you need to check with the guys from https://smpl-x.is.tue.mpg.de/ and https://smplify.is.tue.mpg.de/

I dont have connection with them
