### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by Zscqy17** [carlosedubarreto/frankmocap_win_install#39]
![image](https://user-images.githubusercontent.com/53066625/148203987-fe8c7cb2-4207-4af7-9a1f-685aaf9693c2.png)
 Can anybody help?

**Comment by Zscqy17** [comment]
I have fixed it by downloading SMPLX_HAND_INFO.pkl again. Now, the whole project run well.

**Comment by carlosedubarreto** [comment]
Great, thank for sharing the info
