### ISSUE TITLE
problems with install_pose2d.py, install_hand_detectors.py, build develop

### ISSUE THREAD

**Issue by gdelsmeto** [carlosedubarreto/frankmocap_win_install#4]
Hey, having some issues at the end of the installation. After re-installing a few times the last week... I still can't get it out where I got in to the fog... can anyone help me out? and yes... I know... also python is something.... brandnew... (4 me)
Thanks for... the effort....

(frankmocap) c:\MOCAP\frankmocap>python scripts_py/install_pose2d.py
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "C:\Users\user\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\user\miniconda3\envs\frankmocap\lib\site-packages\git\cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts_py/install_pose2d.py", line 3, in <module>
    import git
  File "C:\Users\user\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

(frankmocap) c:\MOCAP\frankmocap>echo Download extra data for body module
Download extra data for body module
(frankmocap) c:\MOCAP\frankmocap>echo Download extra data for body module
Download extra data for body module

(frankmocap) c:\MOCAP\frankmocap>python scripts_py/download_data_body_module.py
Creation of the directory c:\MOCAP\frankmocap/extra_data/body_module failed
Downloading: data.tar.gz
Traceback (most recent call last):
  File "scripts_py/download_data_body_module.py", line 32, in <module>
FileExistsError: [WinError 183] Kan geen bestand maken dat al bestaat: 'data' -> 'data_from_spin'

(frankmocap) c:\MOCAP\frankmocap>echo Installing a third-party hand detector
Installing a third-party hand detector

(frankmocap) c:\MOCAP\frankmocap>python scripts_py/install_hand_detectors.py
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "C:\Users\user\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\user\miniconda3\envs\frankmocap\lib\site-packages\git\cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts_py/install_hand_detectors.py", line 3, in <module>
    import git,gdown
  File "C:\Users\user\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

(frankmocap) c:\MOCAP\frankmocap>rem installing the hand object detector

(frankmocap) c:\MOCAP\frankmocap>REM "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

(frankmocap) c:\MOCAP\frankmocap>set DISTUTILS_USE_SDK=1

(frankmocap) c:\MOCAP\frankmocap>cd detectors\hand_object_detector\lib

(frankmocap) c:\MOCAP\frankmocap\detectors\hand_object_detector\lib>python setup.py build develop
non-existing path in '.': '_check_build.pyx'
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'develop'

(frankmocap) c:\MOCAP\frankmocap\detectors\hand_object_detector\lib>cd ../../..

(frankmocap) c:\MOCAP\frankmocap>echo Download extra data for hand module
Download extra data for hand module

(frankmocap) c:\MOCAP\frankmocap>python scripts_py/download_data_hand_module.py
Creation of the directory c:\MOCAP\frankmocap/extra_data/hand_module failed
Downloading: SMPLX_HAND_INFO.pkl
Downloading: mean_mano_params.pkl
Creation of the directory c:\MOCAP\frankmocap/extra_data/hand_module/pretrained_weights failed
Downloading: pose_shape_best.pth

(frankmocap) c:\MOCAP\frankmocap>echo Downloading sample videos
Downloading sample videos

(frankmocap) c:\MOCAP\frankmocap>python scripts_py/download_sample_video.py
Downloading: sample_data_frank.tar

**Comment by carlosedubarreto** [comment]
Looks like you are having much more problems than I thought at first.

Are you following the instructions on the video?
Because there are some important things to consider when using this instalation.

Because you will need to compile some code on your machine and for that you will need Visual Studio 2017

Below is the video i'm commenting is this one.
https://www.youtube.com/watch?v=MYLMM7jOMS4

**Comment by carlosedubarreto** [comment]
Closing after long time without responde
