### ISSUE TITLE
Issues with DETECTORS

### ISSUE THREAD

**Issue by gqbay** [carlosedubarreto/frankmocap_win_install#5]
SOLUTION: the installation just was wrong due to GIT absent. So I typed "conda install git" in anaconda, and then ran "install_win_full_body.bat" again. And after that installation is successful! =)) SO HAPPY!

Hello! I want to start with BIG THANK YOU!

And I have some issues. Tried to install step by step.
Everything was just 1:1 copy with you, except 1st moment:

I only have 1 folder in EXTRA_DATA directory, which is BODY_MODULE. There's no HAND_MODULE.
So I continued to follow your instructions. Donloaded everything you said, created smpl folder, etc.

And when I finally tried mocap with the last command "python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl"
it tells me a bunch of "incorrect"

I've attached the ALL ANACONDA PROMPT to this message. Please, help! =)
anaconda promt.txt

IMPORTANT. I'm totally new to GITHUB, AI, Programming, ETC. I came from CG. And CMD is like an undiscovered space for me.
I suppose this error might be because I don't even have an input video file?..

UPD1: 

Noticed this ERRORS after >install_win_full_body.bat

(frankmocap) d:\AI\FRANKMOCAP\frankmocap>rem installing the hand object detector

(frankmocap) d:\AI\FRANKMOCAP\frankmocap>REM "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

(frankmocap) d:\AI\FRANKMOCAP\frankmocap>set DISTUTILS_USE_SDK=1

(frankmocap) d:\AI\FRANKMOCAP\frankmocap>cd detectors\hand_object_detector\lib
The system cannot find the path specified.

(frankmocap) d:\AI\FRANKMOCAP\frankmocap>python setup.py build develop
python: can't open file 'setup.py': [Errno 2] No such file or directory

(frankmocap) d:\AI\FRANKMOCAP\frankmocap>cd ../../..

(frankmocap) d:>echo Download extra data for hand module
Download extra data for hand module

(frankmocap) d:>python scripts_py/download_data_hand_module.py
python: can't open file 'scripts_py/download_data_hand_module.py': [Errno 2] No such file or directory

(frankmocap) d:>echo Downloading sample videos
Downloading sample videos

(frankmocap) d:>python scripts_py/download_sample_video.py
python: can't open file 'scripts_py/download_sample_video.py': [Errno 2] No such file or directory

UPD2: 
followings are missing!
./detectors/
├── body_pose_estimator
├── hand_object_detector
└── hand_only_detector
[anaconda promt.txt](https://github.com/carlosedubarreto/frankmocap_win_install/files/5926198/anaconda.promt.txt)

**Comment by gqbay** [comment]
UPD3: 
downloaded CYGWIN to RUN this script: sh scripts/install_frankmocap.sh

 seeing this literally now: 
 Downloading...
From: https://drive.google.com/uc?id=1H2tWsZkS7tDF8q1-jdjx6V9XrK25EDbE
To: D:\AI\FRANKMOCAP\faster_rcnn_1_8_132028.pth
378MB [02:33, 2.46MB/s]
Downloading...
From: https://drive.google.com/uc?id=1OqgexNM52uxsPG3i8GuodDOJAGFsYkPg
To: D:\AI\FRANKMOCAP\model_0529999.pth
112MB [00:45, 2.52MB/s]


And the detectors folder have just appeared. But still empty. Waiting for downloading completes

**Comment by gqbay** [comment]
UPD4: detectors still empty.

there are some errors 

BAY@BAY /cygdrive/d/AI/FRANKMOCAP/frankmocap
$ sh scripts/install_frankmocap.sh

>>  Installing a third-party 2D keypoint detector
scripts/install_pose2d.sh: line 8: git: command not found
scripts/install_pose2d.sh: line 10: git: command not found
mv: cannot stat 'lightweight-human-pose-estimation.pytorch': No such file or directory
scripts/install_pose2d.sh: line 15: wget: command not found
mv: cannot stat '*.pth': No such file or directory

>>  Download extra data for body module
+ mkdir -p extra_data/body_module
+ cd extra_data/body_module
+ echo 'Downloading extra data from SPIN'
Downloading extra data from SPIN
+ wget http://visiondata.cis.upenn.edu/spin/data.tar.gz
scripts/download_data_body_module.sh: line 11: wget: command not found
+ mv data data_from_spin
+ echo 'Downloading pretrained model'
Downloading pretrained model
+ mkdir -p pretrained_weights
+ cd pretrained_weights
+ wget https://dl.fbaipublicfiles.com/eft/2020_05_31-00_50_43-best-51.749683916568756.pt
scripts/download_data_body_module.sh: line 17: wget: command not found

>>  Installing a third-party hand detector
Collecting gdown
  Using cached gdown-3.12.2.tar.gz (8.2 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting tqdm
  Using cached tqdm-4.56.0-py2.py3-none-any.whl (72 kB)
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting requests[socks]
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting filelock
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 726 kB/s
Collecting PySocks!=1.5.7,>=1.5.6; extra == "socks"
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Building wheels for collected packages: gdown
  Building wheel for gdown (PEP 517) ... done
Successfully built gdown
Installing collected packages: tqdm, six, chardet, urllib3, idna, certifi, PySocks, requests, filelock, g
Socks, requests, filelock, gdown
Successfully installed PySocks-1.7.1 certifi-2020.12.5 chardet-4.0.0 filelock
-3.0.12 gdown-3.12.2 idna-2.10 requests-2.25.1 six-1.15.0 tqdm-4.56.0 urllib3le.
-1.26.3
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is availab
le.
You should consider upgrading via the 'c:\users\administrator\appdata\local\p
rograms\python\python39\python.exe -m pip install --upgrade pip' command.    such file or directory
scripts/install_hand_detectors.sh: line 11: git: command not found
scripts/install_hand_detectors.sh: line 13: git: command not found
scripts/install_hand_detectors.sh: line 16: cd: hand_object_detector/lib: No
such file or directory
C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe: can
't open file 'D:\AI\FRANKMOCAP\frankmocap\detectors\setup.py': [Errno 2] No s
uch file or directory
scripts/install_hand_detectors.sh: line 21: git: command not found
scripts/install_hand_detectors.sh: line 23: git: command not found
mv: cannot stat 'hand_detector.d2': No such file or directory
Downloading...
From: https://drive.google.com/uc?id=1H2tWsZkS7tDF8q1-jdjx6V9XrK25EDbE
To: D:\AI\FRANKMOCAP\faster_rcnn_1_8_132028.pth
378MB [02:33, 2.46MB/s]
Downloading...
From: https://drive.google.com/uc?id=1OqgexNM52uxsPG3i8GuodDOJAGFsYkPg
To: D:\AI\FRANKMOCAP\model_0529999.pth
115MB [00:46, 2.20MB/s]

BAY@BAY /cygdrive/d/AI/FRANKMOCAP/frankmocap

**Comment by carlosedubarreto** [comment]
Thanks a lot for sharing your experience and the solution you´ve found.

There is a gitpython instalation on the requeiremente file, but you should have some problems with the instalation of git via PIP, I'm happy to know that it worked with conda.

**Comment by monacv** [comment]
do you know if 2020_05_31-00_50_43-best-51.749683916568756.pt is for full body mocap with hands or only full body?

**Comment by carlosedubarreto** [comment]
Hi @monacv 
I dont know what is 
2020_05_31-00_50_43-best-51.749683916568756.pt
😅

this sort of questions is better to be asked on the frankmocap github
https://github.com/facebookresearch/frankmocap
