### ISSUE TITLE
I Keep Getting This Error

### ISSUE THREAD

**Issue by moustafaahmed365** [carlosedubarreto/frankmocap_win_install#6]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
virtualenv 20.0.27 requires appdirs<2,>=1.4.3, which is not installed.
virtualenv 20.0.27 requires importlib-metadata<2,>=0.12; python_version < "3.8", but you have importlib-metadata 3.4.0 which is incompatible.

**Comment by carlosedubarreto** [comment]
which passes have you done to receive this error?

**Comment by moustafaahmed365** [comment]
I honestly do not know. I followed the instructions from the video you've posted on YouTube.

**Comment by carlosedubarreto** [comment]
can you do the instructions and copy here all the text that shows on the cmd window?

someone else did it and it was easier to find what was the problem.

**Comment by moustafaahmed365** [comment]
(base) C:\Users\moust>cd\

(base) C:\>cd MOCAP

(base) C:\MOCAP>cd frankmocap

(base) C:\MOCAP\frankmocap>conda create -n frankmocap python=3.7
WARNING: A conda environment already exists at 'C:\Users\moust\miniconda3\envs\frankmocap'
Remove existing environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\moust\miniconda3\envs\frankmocap

  added / updated specs:
    - python=3.7


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2021.1.19-haa95532_0
  certifi            pkgs/main/win-64::certifi-2020.12.5-py37haa95532_0
  openssl            pkgs/main/win-64::openssl-1.1.1i-h2bbff1b_0
  pip                pkgs/main/win-64::pip-20.3.3-py37haa95532_0
  python             pkgs/main/win-64::python-3.7.9-h60c2a47_0
  setuptools         pkgs/main/win-64::setuptools-52.0.0-py37haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.33.0-h2a8f88b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_4


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate frankmocap
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\MOCAP\frankmocap>conda activate frankmocap

(frankmocap) C:\MOCAP\frankmocap>conda install cudatoolkit=10.1 cudnn=7.6.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\moust\miniconda3\envs\frankmocap

  added / updated specs:
    - cudatoolkit=10.1
    - cudnn=7.6.0


The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/win-64::cudatoolkit-10.1.243-h74a9793_0
  cudnn              pkgs/main/win-64::cudnn-7.6.0-cuda10.1_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(frankmocap) C:\MOCAP\frankmocap>conda install -c pytorch pytorch==1.6.0 torchvision cudatoolkit=10.1
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\moust\miniconda3\envs\frankmocap

  added / updated specs:
    - cudatoolkit=10.1
    - pytorch==1.6.0
    - torchvision


The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  freetype           pkgs/main/win-64::freetype-2.10.4-hd328e21_0
  intel-openmp       pkgs/main/win-64::intel-openmp-2020.2-254
  jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libtiff            pkgs/main/win-64::libtiff-4.1.0-h56a325e_1
  lz4-c              pkgs/main/win-64::lz4-c-1.9.3-h2bbff1b_0
  mkl                pkgs/main/win-64::mkl-2020.2-256
  mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py37h196d8e1_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.2.0-py37h45dec08_0
  mkl_random         pkgs/main/win-64::mkl_random-1.1.1-py37h47e9c7a_0
  ninja              pkgs/main/win-64::ninja-1.10.2-py37h6d14046_0
  numpy              pkgs/main/win-64::numpy-1.19.2-py37hadc3359_0
  numpy-base         pkgs/main/win-64::numpy-base-1.19.2-py37ha3acd2a_0
  olefile            pkgs/main/win-64::olefile-0.46-py37_0
  pillow             pkgs/main/win-64::pillow-8.1.0-py37h4fa10fc_0
  pytorch            pytorch/win-64::pytorch-1.6.0-py3.7_cuda101_cudnn7_0
  six                pkgs/main/win-64::six-1.15.0-py37haa95532_0
  tk                 pkgs/main/win-64::tk-8.6.10-he774522_0
  torchvision        pytorch/win-64::torchvision-0.7.0-py37_cu101
  xz                 pkgs/main/win-64::xz-5.2.5-h62dcd97_0
  zstd               pkgs/main/win-64::zstd-1.4.5-h04227a9_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(frankmocap) C:\MOCAP\frankmocap>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.32
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

(frankmocap) C:\MOCAP\frankmocap>install_win_full_body.bat

(frankmocap) C:\MOCAP\frankmocap>rem ####### installing files pre packed

(frankmocap) C:\MOCAP\frankmocap>REM pip install whl/faster_rcnn-0.1-cp37-cp37m-win_amd64.whl

(frankmocap) C:\MOCAP\frankmocap>pip install whl/detectron2-0.3-cp37-cp37m-win_amd64.whl
Processing c:\mocap\frankmocap\whl\detectron2-0.3-cp37-cp37m-win_amd64.whl
Requirement already satisfied: Pillow>=7.1 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from detectron2==0.3) (8.1.0)
Collecting fvcore>=0.1.2
  Using cached fvcore-0.1.3.post20210213-py3-none-any.whl
Requirement already satisfied: numpy in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from fvcore>=0.1.2->detectron2==0.3) (1.19.2)
Collecting iopath>=0.1.2
  Using cached iopath-0.1.3-py3-none-any.whl
Collecting pycocotools>=2.0.2
  Using cached pycocotools-2.0.2-cp37-cp37m-win_amd64.whl
Requirement already satisfied: setuptools>=18.0 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from pycocotools>=2.0.2->detectron2==0.3) (52.0.0.post20210125)
Collecting cython>=0.27.3
  Using cached Cython-0.29.21-cp37-cp37m-win_amd64.whl (1.6 MB)
Collecting matplotlib
  Using cached matplotlib-3.3.4-cp37-cp37m-win_amd64.whl (8.5 MB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: six in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from cycler>=0.10->matplotlib->detectron2==0.3) (1.15.0)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp37-cp37m-win_amd64.whl (51 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyyaml>=5.1
  Using cached PyYAML-5.4.1-cp37-cp37m-win_amd64.whl (210 kB)
Collecting termcolor>=1.1
  Using cached termcolor-1.1.0-py3-none-any.whl
Collecting tqdm>4.29.0
  Using cached tqdm-4.56.2-py2.py3-none-any.whl (72 kB)
Collecting yacs>=0.1.6
  Using cached yacs-0.1.8-py3-none-any.whl (14 kB)
Collecting cloudpickle
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Collecting portalocker
  Using cached portalocker-2.2.1-py2.py3-none-any.whl (15 kB)
Collecting pywin32!=226
  Using cached pywin32-300-cp37-cp37m-win_amd64.whl (9.2 MB)
Collecting pydot
  Using cached pydot-1.4.1-py2.py3-none-any.whl (19 kB)
Collecting tabulate
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting tensorboard
  Using cached tensorboard-2.4.1-py3-none-any.whl (10.6 MB)
Requirement already satisfied: wheel>=0.26 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from tensorboard->detectron2==0.3) (0.36.2)
Collecting absl-py>=0.4
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.26.1-py2.py3-none-any.whl (116 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.1-py3-none-any.whl (12 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.2-py2.py3-none-any.whl (18 kB)
Collecting grpcio>=1.24.3
  Using cached grpcio-1.35.0-cp37-cp37m-win_amd64.whl (3.0 MB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.3-py3-none-any.whl (96 kB)
Collecting protobuf>=3.6.0
  Using cached protobuf-3.14.0-cp37-cp37m-win_amd64.whl (798 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting requests<3,>=2.21.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3) (2020.12.5)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.7-py3-none-any.whl (34 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-3.4.0-py3-none-any.whl (10 kB)
Collecting typing-extensions>=3.6.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting zipp>=0.5
  Using cached zipp-3.4.0-py3-none-any.whl (5.2 kB)
Installing collected packages: urllib3, pyasn1, idna, chardet, zipp, typing-extensions, rsa, requests, pywin32, pyasn1-modules, oauthlib, cachetools, tqdm, requests-oauthlib, pyyaml, python-dateutil, pyparsing, portalocker, kiwisolver, importlib-metadata, google-auth, cycler, yacs, werkzeug, termcolor, tensorboard-plugin-wit, tabulate, protobuf, matplotlib, markdown, iopath, grpcio, google-auth-oauthlib, cython, absl-py, tensorboard, pydot, pycocotools, fvcore, future, cloudpickle, detectron2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
virtualenv 20.0.27 requires appdirs<2,>=1.4.3, which is not installed.
virtualenv 20.0.27 requires importlib-metadata<2,>=0.12; python_version < "3.8", but you have importlib-metadata 3.4.0 which is incompatible.
Successfully installed absl-py-0.11.0 cachetools-4.2.1 chardet-4.0.0 cloudpickle-1.6.0 cycler-0.10.0 cython-0.29.21 detectron2-0.3 future-0.18.2 fvcore-0.1.3.post20210213 google-auth-1.26.1 google-auth-oauthlib-0.4.2 grpcio-1.35.0 idna-2.10 importlib-metadata-3.4.0 iopath-0.1.3 kiwisolver-1.3.1 markdown-3.3.3 matplotlib-3.3.4 oauthlib-3.1.0 portalocker-2.2.1 protobuf-3.14.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycocotools-2.0.2 pydot-1.4.1 pyparsing-2.4.7 python-dateutil-2.8.1 pywin32-300 pyyaml-5.4.1 requests-2.25.1 requests-oauthlib-1.3.0 rsa-4.7 tabulate-0.8.7 tensorboard-2.4.1 tensorboard-plugin-wit-1.8.0 termcolor-1.1.0 tqdm-4.56.2 typing-extensions-3.7.4.3 urllib3-1.26.3 werkzeug-1.0.1 yacs-0.1.8 zipp-3.4.0

(frankmocap) C:\MOCAP\frankmocap>pip install whl/opendr-0.73-py3-none-any.whl
Processing c:\mocap\frankmocap\whl\opendr-0.73-py3-none-any.whl
Requirement already satisfied: matplotlib in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from opendr==0.73) (3.3.4)
Requirement already satisfied: Cython in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from opendr==0.73) (0.29.21)
Collecting chumpy>=0.58
  Using cached chumpy-0.70-py3-none-any.whl
Requirement already satisfied: six>=1.11.0 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from chumpy>=0.58->opendr==0.73) (1.15.0)
Collecting scipy>=0.13.0
  Using cached scipy-1.6.0-cp37-cp37m-win_amd64.whl (32.5 MB)
Requirement already satisfied: numpy>=1.16.5 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from scipy>=0.13.0->chumpy>=0.58->opendr==0.73) (1.19.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from matplotlib->opendr==0.73) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from matplotlib->opendr==0.73) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from matplotlib->opendr==0.73) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from matplotlib->opendr==0.73) (8.1.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from matplotlib->opendr==0.73) (1.3.1)
Installing collected packages: scipy, chumpy, opendr
Successfully installed chumpy-0.70 opendr-0.73 scipy-1.6.0

(frankmocap) C:\MOCAP\frankmocap>pip install whl/PyOpenGL-3.1.5-cp37-cp37m-win_amd64.whl
Processing c:\mocap\frankmocap\whl\pyopengl-3.1.5-cp37-cp37m-win_amd64.whl
Installing collected packages: PyOpenGL
Successfully installed PyOpenGL-3.1.5

(frankmocap) C:\MOCAP\frankmocap>pip install whl/PyOpenGL_accelerate-3.1.5-cp37-cp37m-win_amd64.whl
Processing c:\mocap\frankmocap\whl\pyopengl_accelerate-3.1.5-cp37-cp37m-win_amd64.whl
Installing collected packages: PyOpenGL-accelerate
Successfully installed PyOpenGL-accelerate-3.1.5

(frankmocap) C:\MOCAP\frankmocap>pip install -r requirements_alter.txt
Requirement already satisfied: pip in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 1)) (20.3.3)
Requirement already satisfied: requests in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 3)) (2.25.1)
Requirement already satisfied: pycocotools in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 6)) (2.0.2)
Requirement already satisfied: scipy in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 9)) (1.6.0)
Requirement already satisfied: pillow>=7.1.0 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 10)) (8.1.0)
Requirement already satisfied: cython in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 12)) (0.29.21)
Requirement already satisfied: pyyaml in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 16)) (5.4.1)
Requirement already satisfied: tqdm in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 18)) (4.56.2)
Requirement already satisfied: opendr in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 22)) (0.73)
Requirement already satisfied: chumpy in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from -r requirements_alter.txt (line 23)) (0.70)
Collecting cffi
  Using cached cffi-1.14.5-cp37-cp37m-win_amd64.whl (178 kB)
Requirement already satisfied: six>=1.11.0 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from chumpy->-r requirements_alter.txt (line 23)) (1.15.0)
Requirement already satisfied: numpy>=1.16.5 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from scipy->-r requirements_alter.txt (line 9)) (1.19.2)
Collecting easydict
  Using cached easydict-1.9-py3-none-any.whl
Collecting gdown
  Using cached gdown-3.12.2-py3-none-any.whl
Requirement already satisfied: filelock in c:\users\moust\appdata\roaming\python\python37\site-packages (from gdown->-r requirements_alter.txt (line 2)) (3.0.12)
Collecting gitpython
  Using cached GitPython-3.1.13-py3-none-any.whl (159 kB)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.5-py3-none-any.whl (63 kB)
Collecting smmap<4,>=3.0.1
  Using cached smmap-3.0.5-py2.py3-none-any.whl (25 kB)
Collecting jinja2
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp37-cp37m-win_amd64.whl (16 kB)
Collecting msgpack
  Using cached msgpack-1.0.2-cp37-cp37m-win_amd64.whl (68 kB)
Collecting opencv-python
  Using cached opencv_python-4.5.1.48-cp37-cp37m-win_amd64.whl (34.9 MB)
Requirement already satisfied: matplotlib in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from opendr->-r requirements_alter.txt (line 22)) (3.3.4)
Collecting pafy
  Using cached pafy-0.5.5-py2.py3-none-any.whl (35 kB)
Requirement already satisfied: setuptools>=18.0 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from pycocotools->-r requirements_alter.txt (line 6)) (52.0.0.post20210125)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from matplotlib->opendr->-r requirements_alter.txt (line 22)) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from matplotlib->opendr->-r requirements_alter.txt (line 22)) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from matplotlib->opendr->-r requirements_alter.txt (line 22)) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from matplotlib->opendr->-r requirements_alter.txt (line 22)) (1.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from requests->-r requirements_alter.txt (line 3)) (1.26.3)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from requests->-r requirements_alter.txt (line 3)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from requests->-r requirements_alter.txt (line 3)) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from requests->-r requirements_alter.txt (line 3)) (2.10)
Collecting sklearn
  Using cached sklearn-0.0-py2.py3-none-any.whl
Collecting smplx
  Using cached smplx-0.1.26-py3-none-any.whl (29 kB)
Requirement already satisfied: torch>=1.0.1.post2 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from smplx->-r requirements_alter.txt (line 20)) (1.6.0)
Requirement already satisfied: future in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from torch>=1.0.1.post2->smplx->-r requirements_alter.txt (line 20)) (0.18.2)
Collecting torchgeometry>=0.1.2
  Using cached torchgeometry-0.1.2-py2.py3-none-any.whl (42 kB)
Collecting tensorboardX
  Using cached tensorboardX-2.1-py2.py3-none-any.whl (308 kB)
Requirement already satisfied: protobuf>=3.8.0 in c:\users\moust\miniconda3\envs\frankmocap\lib\site-packages (from tensorboardX->-r requirements_alter.txt (line 17)) (3.14.0)
Collecting youtube-dl
  Using cached youtube_dl-2021.2.10-py2.py3-none-any.whl (1.9 MB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting PySocks!=1.5.7,>=1.5.6
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting scikit-learn
  Using cached scikit_learn-0.24.1-cp37-cp37m-win_amd64.whl (6.8 MB)
Collecting joblib>=0.11
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Installing collected packages: threadpoolctl, smmap, PySocks, joblib, torchgeometry, scikit-learn, pycparser, MarkupSafe, gitdb, youtube-dl, tensorboardX, smplx, sklearn, pafy, opencv-python, msgpack, jinja2, gitpython, gdown, easydict, cffi
Successfully installed MarkupSafe-1.1.1 PySocks-1.7.1 cffi-1.14.5 easydict-1.9 gdown-3.12.2 gitdb-4.0.5 gitpython-3.1.13 jinja2-2.11.3 joblib-1.0.1 msgpack-1.0.2 opencv-python-4.5.1.48 pafy-0.5.5 pycparser-2.20 scikit-learn-0.24.1 sklearn-0.0 smmap-3.0.5 smplx-0.1.26 tensorboardX-2.1 threadpoolctl-2.1.0 torchgeometry-0.1.2 youtube-dl-2021.2.10

(frankmocap) C:\MOCAP\frankmocap>echo Installing a third-party 2D keypoint detector
Installing a third-party 2D keypoint detector

(frankmocap) C:\MOCAP\frankmocap>python scripts_py/install_pose2d.py
Traceback (most recent call last):
  File "C:\Users\moust\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "C:\Users\moust\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\moust\miniconda3\envs\frankmocap\lib\site-packages\git\cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts_py/install_pose2d.py", line 3, in <module>
    import git
  File "C:\Users\moust\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


(frankmocap) C:\MOCAP\frankmocap>echo Download extra data for body module
Download extra data for body module

(frankmocap) C:\MOCAP\frankmocap>python scripts_py/download_data_body_module.py
Creation of the directory C:\MOCAP\frankmocap/extra_data/body_module failed
Downloading: data.tar.gz
Traceback (most recent call last):
  File "scripts_py/download_data_body_module.py", line 32, in <module>
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data' -> 'data_from_spin'

(frankmocap) C:\MOCAP\frankmocap>echo Installing a third-party hand detector
Installing a third-party hand detector

(frankmocap) C:\MOCAP\frankmocap>python scripts_py/install_hand_detectors.py
Traceback (most recent call last):
  File "C:\Users\moust\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "C:\Users\moust\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\moust\miniconda3\envs\frankmocap\lib\site-packages\git\cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts_py/install_hand_detectors.py", line 3, in <module>
    import git,gdown
  File "C:\Users\moust\miniconda3\envs\frankmocap\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


(frankmocap) C:\MOCAP\frankmocap>rem installing the hand object detector

(frankmocap) C:\MOCAP\frankmocap>REM "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

(frankmocap) C:\MOCAP\frankmocap>set DISTUTILS_USE_SDK=1

(frankmocap) C:\MOCAP\frankmocap>cd detectors\hand_object_detector\lib
The system cannot find the path specified.

(frankmocap) C:\MOCAP\frankmocap>python setup.py build develop
python: can't open file 'setup.py': [Errno 2] No such file or directory

(frankmocap) C:\MOCAP\frankmocap>cd ../../..

(frankmocap) C:\>echo Download extra data for hand module
Download extra data for hand module

(frankmocap) C:\>python scripts_py/download_data_hand_module.py
python: can't open file 'scripts_py/download_data_hand_module.py': [Errno 2] No such file or directory

(frankmocap) C:\>echo Downloading sample videos
Downloading sample videos

(frankmocap) C:\>python scripts_py/download_sample_video.py
python: can't open file 'scripts_py/download_sample_video.py': [Errno 2] No such file or directory

**Comment by carlosedubarreto** [comment]
Looks like you have a problem with the python git package

I didnt try the anaconda git installation, but please, try this command.

conda install -c anaconda git

then, run the "install_win_full_body.bat" again

**Comment by moustafaahmed365** [comment]
It fixed the issue. Thank You
