### ISSUE TITLE
Problems at the end of installation (hands and video demo)

### ISSUE THREAD

**Issue by Kyoin** [carlosedubarreto/frankmocap_win_install#8]
Good morning,
I've already watched your tutorial about installing frankmocap on Windows, however, I have two big issues that I'm not able to solve apparently. At the end of the installation conda seems not to find the path to the repository of the hands and video.
I've checked more and more times, I have the right programs with the right versions (CUDA 10.0, for example) but I cannot go ahead and finish the installation.
This is the code:

`(base) C:\MOCAP\frankmocap>python setup.py build develop
python: can't open file 'setup.py': [Errno 2] No such file or directory

(base) C:\MOCAP\frankmocap>cd ../../..

(base) C:\>echo Download extra data for hand module
Download extra data for hand module

(base) C:\>python scripts_py/download_data_hand_module.py
python: can't open file 'scripts_py/download_data_hand_module.py': [Errno 2] No such file or directory

(base) C:\>echo Downloading sample videos
Downloading sample videos

(base) C:\>python scripts_py/download_sample_video.py
python: can't open file 'scripts_py/download_sample_video.py': [Errno 2] No such file or directory`

what should I do?

Thanks in advance

**Comment by carlosedubarreto** [comment]
Probably you have problems with the git installation.
please try this
`conda install -c anaconda git`

then run the installation again

**Comment by Kyoin** [comment]
Ok thanks I'll let you know!

**Comment by Kyoin** [comment]
Nothing to do it gives me the same error.
![problems with installation](https://user-images.githubusercontent.com/47851332/112440895-23588700-8d4b-11eb-8078-b05728eca60b.png)

**Comment by carlosedubarreto** [comment]
can you see if this files exists?
![image](https://user-images.githubusercontent.com/4061130/112441962-1e371000-8d2a-11eb-8d90-80c0bf9e275b.png)

**Comment by Kyoin** [comment]
No, I don't have that folder "detectors"...!
![problems with installation2](https://user-images.githubusercontent.com/47851332/112442532-37e94f00-8d4c-11eb-8e53-5e54dbdc042e.png)

**Comment by carlosedubarreto** [comment]
Now I notice something more odd....
Your computer doesnt seem to have the scripts to do the installation
does it have these files?
![image](https://user-images.githubusercontent.com/4061130/112442455-9bfb1b80-8d2a-11eb-8176-a0dddde81b82.png)

**Comment by Kyoin** [comment]
Yes. I have those.

**Comment by carlosedubarreto** [comment]
please run only this line

`python scripts_py/install_hand_detectors.py `

on the frankmocap root folder
and show me what happens

**Comment by Kyoin** [comment]
Like this?
![problems with installation3](https://user-images.githubusercontent.com/47851332/112443252-058c2180-8d4d-11eb-9c3f-1850b733f627.png)

**Comment by carlosedubarreto** [comment]
yep, now run this and shoe me the result, please

`conda install -c anaconda git`

One notice, you are not in the frankmocap virtualenviroment.

maybe the problem is that you did the git instalation inside the virtual enviroment.;

Maybe you should got back the and activate it.

If you followed the instructions, you virtualenviroment should be activated doing:

`conda activate frankmocap`

**Comment by Kyoin** [comment]
Here
![problems with installation4](https://user-images.githubusercontent.com/47851332/112443629-79c6c500-8d4d-11eb-957e-c9b945f0fc0f.png)

**Comment by carlosedubarreto** [comment]
One notice, you are not in the frankmocap virtualenviroment.

maybe the problem is that you did the git instalation inside the virtual enviroment.;

Maybe you should got back the and activate it.

If you followed the instructions, you virtualenviroment should be activated doing:

`conda activate frankmocap`

`conda install -c anaconda git`
en then run again
`python scripts_py/install_hand_detectors.py`

**Comment by Kyoin** [comment]
That was right, but I still miss that folder!
![problems with installation5](https://user-images.githubusercontent.com/47851332/112444239-2012ca80-8d4e-11eb-9ceb-b48c236e28b8.png)

**Comment by carlosedubarreto** [comment]
[install_hand_detectors_alter.zip](https://github.com/carlosedubarreto/frankmocap_win_install/files/6203215/install_hand_detectors_alter.zip)

please unpack inside the folder scripts_py an run this:
python scripts_py/install_hand_detectors_alter.py

and show what happens

**Comment by Kyoin** [comment]
Same error.
![problems with installation6](https://user-images.githubusercontent.com/47851332/112445199-2bb2c100-8d4f-11eb-8d31-5ac34dd3159f.png)

**Comment by carlosedubarreto** [comment]
[install_hand_detectors_alter.zip](https://github.com/carlosedubarreto/frankmocap_win_install/files/6203247/install_hand_detectors_alter.zip)

Yeah, i saw that I missed a place.
unpack this file instead and run 

`python scripts_py/install_hand_detectors_alter.py`

**Comment by Kyoin** [comment]
It gives me the same advice:
![problems with installation7](https://user-images.githubusercontent.com/47851332/112445928-f5297600-8d4f-11eb-937d-61f71a3a6ca7.png)

**Comment by carlosedubarreto** [comment]
please create "detectors" folder manually.

and try again.
the full path should be
C:\MOCAP\frankmocap\detectors

**Comment by carlosedubarreto** [comment]
sorry I saw some other thing, this error is showing because of a problem on install pose_2d.py script.

as it is created over there.
I gues if you create that folder manually, some other thing wont work.


I think the best to be done is run the installation and put here the full installation text, so I can see where the problems show up.

Because each script depends on a previous one.


Probably i'll take longer to answer because I have some things to do, and I'm a little late here 😊

**Comment by Kyoin** [comment]
Ok thank you really much, in fact as I created the folder some files were downloaded. But if you think that is better to send you the whole thing I'll do it!
![problems with installation8](https://user-images.githubusercontent.com/47851332/112448106-54888580-8d52-11eb-95c1-482df3804f6a.png)
![problems with installation9](https://user-images.githubusercontent.com/47851332/112448108-55211c00-8d52-11eb-9ba8-6143d323bce2.png)

**Comment by carlosedubarreto** [comment]
The better suggestion I have is. 

delete the frankmocap folder and do the tutorial from the beggining, but running `conda install -c anaconda git` before executing the `install_win_full_body.bat`

and copy and paste the full text that shows on your screen here. so I can analyse where the problem beggins

**Comment by Kyoin** [comment]
IT WORKED!
Doing what you said before, i could finish the installation and see the demo.
Thank you so much for your patience!!!

**Comment by carlosedubarreto** [comment]
that is great. have fun 😊
